import matplotlib.pyplot as plt
import numpy as a
x=a.arange(0,10,0.1)
w=a.arange(0,1,0.1)
b=a.arange(-10,10,0.1)
d=a.arange(-10,10,0.1)
y=a.exp(x)
plt.figure(1)
plt.plot(x,y)
plt.title('exponential')
plt.xlabel('time')
plt.ylabel('amplitude')
z=a.arcsin(w)
plt.figure(2)
plt.plot(w,z)
plt.title('inverse')
plt.xlabel('time')
plt.ylabel('amplitude')
c=a.arctan(b)
plt.figure(3)
plt.plot(b,c)
plt.title('inverse tan')
plt.xlabel('time')
plt.ylabel('amplitude')
e=a.sinc(d)
plt.figure(4)
plt.plot(d,e)
plt.title('sinc')
plt.xlabel('time')
plt.ylabel('amplitude')
plt.show()
